### ISSUE TITLE
[Question] How to set the value of an atom in `mutationFn`?

### ISSUE THREAD

**Issue by ahhshm** [jotaijs/jotai-tanstack-query#26] opened 2023-03-04 07:52 UTC
I need to set the value of an atom in `atomsWithMutation`:
```ts
const xAtom = atom(0)

const [, postAtom] = atomsWithMutation((get) => ({
  mutationFn: async (x) => {
    const data = await fetch(/* ... */)
    const { x } = data    
    // set the value of `xAtom` to `x`
    return data
  },
}))
```
I was hoping that `atomsWithMutation` gives me access to a `set` function that I can use here but that's not the case and I can guess why. 

The question is what's the best way to set the value of an atom based on the return value of a mutation?

The only solution I can think of is using a `store` that can be used outside of react.

**Comment by dai-shi** [comment] 2023-03-04 08:01
Duplicate of #22.

**Closed** 2023-03-04 08:20 UTC
